
title: Team Armin Soyka
org_title: Team Armin Soyka

name: Armin Soyka
shortname: Armin

privacy_officer_email: <a href="mailto:arminsoyka@c3o.org">Christopher Clay</a>

sharing_title: Ich unterstütze das Team Armin Soyka
sharing_body: Armin tritt bei der Wien Wahl 2010 an. Wär doch cool, wenn er es schaffen würde.

elsewhere_link_url: http://pressearminsoyka.soup.io
elsewhere_iframe_url: http://pressearminsoyka.soup.io/mini/430/30?css=http://test.arminsoyka.at/stylesheets/soup.css

progress_required_users: 100
